CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1;

CREATE TABLE "PUBLIC"."ALBUM"(
    "ID" BIGINT NOT NULL,
    "TITLE" VARCHAR(255),
    "USER_ID" BIGINT
);

ALTER TABLE "PUBLIC"."ALBUM" 
ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");